In [1]:
import torch

In [2]:

t = torch.tensor([[0,1,2,3,],[10,11,12,13],[20,21,22,23],[30,31,32,33]])
input1 = t.view(1, 1, 4, 4).float()
input2 = 100+t.view(1, 1, 4, 4).float()
input3 = 200+t.view(1, 1, 4, 4).float()



In [3]:
print(input1)
print(input2)
print(input3)


tensor([[[[ 0.,  1.,  2.,  3.],
          [10., 11., 12., 13.],
          [20., 21., 22., 23.],
          [30., 31., 32., 33.]]]])
tensor([[[[100., 101., 102., 103.],
          [110., 111., 112., 113.],
          [120., 121., 122., 123.],
          [130., 131., 132., 133.]]]])
tensor([[[[200., 201., 202., 203.],
          [210., 211., 212., 213.],
          [220., 221., 222., 223.],
          [230., 231., 232., 233.]]]])


In [4]:
input = torch.stack((input1,input2,input3),2)

In [5]:
print(input.shape)
print(input)

torch.Size([1, 1, 3, 4, 4])
tensor([[[[[  0.,   1.,   2.,   3.],
           [ 10.,  11.,  12.,  13.],
           [ 20.,  21.,  22.,  23.],
           [ 30.,  31.,  32.,  33.]],

          [[100., 101., 102., 103.],
           [110., 111., 112., 113.],
           [120., 121., 122., 123.],
           [130., 131., 132., 133.]],

          [[200., 201., 202., 203.],
           [210., 211., 212., 213.],
           [220., 221., 222., 223.],
           [230., 231., 232., 233.]]]]])


tensor([[[[[-1.0000, -1.0000, -1.0000],
           [ 0.0000, -1.0000, -0.9000],
           [ 1.0000, -1.0000, -0.8000]],

          [[-1.0000,  0.0000, -0.1000],
           [ 0.0000,  0.0000,  0.0000],
           [ 1.0000,  0.0000,  0.1000]],

          [[-1.0000,  1.0000,  0.8000],
           [ 0.0000,  1.0000,  0.9000],
           [ 1.0000,  1.0000,  1.0000]]]]])

In [6]:
x = torch.Tensor([
    [-1,0,1],
    [-1,0,1],
    [-1,0,1],
])
y = torch.Tensor([
    [-1,-1,-1],
    [0,0,0],
    [1,1,1,],
])
z = torch.Tensor([
    [-1,-.9,-.8],
    [-.1,0,.1],
    [.8,.9,1]
])

In [7]:
grid = torch.stack((x,y,z), 2)
grid = grid.unsqueeze(0) # add batch dim
grid = grid.unsqueeze(0)

In [8]:
grid.shape



torch.Size([1, 1, 3, 3, 3])

In [ ]:
grid

In [10]:
output = torch.nn.functional.grid_sample(input, grid)
print(output)

tensor([[[[[  0.0000,  11.5000,  23.0000],
           [105.0000, 116.5000, 128.0000],
           [210.0000, 221.5000, 233.0000]]]]])


/home/adong/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:2693: UserWarning: Default grid_sample and affine_grid behavior will be changed to align_corners=False from 1.4.0. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior will be changed "


In [11]:
output.shape

torch.Size([1, 1, 1, 3, 3])

In [12]:
112*.2+.8*212

192.00000000000003

# Bilateral grid test

In [60]:
x = torch.arange(0,101,1)
y = torch.arange(0,50,1)



In [61]:

x_grid,y_grid = torch.meshgrid(x,y)

In [62]:
print(x_grid[0,0])
print(y_grid[0,0])

tensor(0)
tensor(0)


In [70]:
print(x_grid[55,49])
print(y_grid[55,49])

tensor(55)
tensor(49)


torch.Size([21, 21])

In [13]:
input = torch.zeros(1,12,8,32,32)
input[0,:,0,0,0] = torch.arange(12)
input[0,:,0,0,0]

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [26]:
x = torch.Tensor([
    [-1,0,],
    [-1,0,]
])
y = torch.Tensor([
    [-1,-1,],
    [1,1,]
])
z = torch.Tensor([
    [-1,-.9,],
    [-.1,0,]
])

In [27]:
grid = torch.stack((x,y,z), 2)
grid = grid.unsqueeze(0) # add batch dim


In [28]:
grid.shape



torch.Size([1, 2, 2, 3])

In [23]:
grid

tensor([[[[-1.0000, -1.0000, -1.0000],
          [ 0.0000, -1.0000, -0.9000],
          [ 1.0000, -1.0000, -0.8000]],

         [[-1.0000,  0.0000, -0.1000],
          [ 0.0000,  0.0000,  0.0000],
          [ 1.0000,  0.0000,  0.1000]],

         [[-1.0000,  1.0000,  0.8000],
          [ 0.0000,  1.0000,  0.9000],
          [ 1.0000,  1.0000,  1.0000]]]])

In [24]:
output = torch.nn.functional.grid_sample(input, grid)
print(output)

RuntimeError: grid_sampler(): expected 4D or 5D input and grid with same number of dimensions, but got input with sizes [1, 12, 8, 32, 32] and grid with sizes [1, 3, 3, 3]

In [15]:
output.shape

torch.Size([1, 12, 1, 3, 3])

In [16]:
print(output[0,:,0,0,0])

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [17]:
output = output.reshape(1,3,4,1,3,3)
output[0,:,:,0,0,0]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])